const hits = [
    {
        id:'1',
        Cover:'https://m.media-amazon.com/images/I/7164ajA6eJS._SL1200_.jpg',
        Album:'College Dropout',
        Song:'Family Buisness',
        Year:'2004',
        Link:'',
    },
    {
        id:'2',
        Cover:'https://m.media-amazon.com/images/I/718khrgr5bL._SL1400_.jpg',
        Album:'Late Registration',
        Song:'Gold Digger',
        Year:'2005',
        Link:'',
    },
    {
        id:'3',
        Cover:'https://m.media-amazon.com/images/I/71pxGj4RoVS._AC_SL1200_.jpg',
        Album:'Graduation',
        Song:'Stonger',
        Year:'2007',
        Link:'',
    },
    {
        id:'4',
        Cover:'https://upload.wikimedia.org/wikipedia/en/f/f1/808s_%26_Heartbreak.png',
        Album:'808s & Heartbreak',
        Song:'Heartless',
        Year:'2008',
        Link:'',
    },
    {
        id:'5',
        Cover:'https://m.media-amazon.com/images/I/91dHRGIV65L._SL1500_.jpg',
        Album:'My Beautiful Dark Twisted Fantasy',
        Song:'Runaway',
        Year:'2010',
        Link:'',
    },
    {
        id:'6',
        Cover:'https://upload.wikimedia.org/wikipedia/en/e/ee/Watch_The_Throne.jpg',
        Album:'Watch The Throne',
        Song:'Otis',
        Year:'2011',
        Link:'',
    },
    {
        id:'7',
        Cover:'https://upload.wikimedia.org/wikipedia/en/0/03/Yeezus_album_cover.png',
        Album:'Yeezus',
        Song:'Bound 2',
        Year:'2013',
        Link:'',
    },
    {
        id:'8',
        Cover:'https://upload.wikimedia.org/wikipedia/en/4/4d/The_life_of_pablo_alternate.jpg',
        Album:'The Life of Pablo',
        Song:'Ultralight Beam',
        Year:'2016',
        Link:'',
    },
    {
        id:'9',
        Cover:'https://pyxis.nymag.com/v1/imgs/699/1e2/965287137d49b3f29e6ff9c4d0e5a3f07b-01-kanye-west-ye.rsquare.w330.jpg',
        Album:'Ye',
        Song:'Violent Crimes',
        Year:'2018',
        Link:'',
    },
    {
        id:'10',
        Cover:'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F11%2Fkanye-west-jesus-is-king-cover-art-cryptic-message-solved-000.jpg?w=960&cbr=1&q=90&fit=max',
        Album:'Jesus is King',
        Song:'',
        Year:'2019',
        Link:'',
    },
    {
        id:'11',
        Cover:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Almost_black_square_020305.png/220px-Almost_black_square_020305.png',
        Album:'Donda',
        Song:'Moon',
        Year:'2021',
        Link:'',
    },
];

export default hits